### ISSUE TITLE
Gracefully handle updates for portable games

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-backend#138]
**Is your feature request related to a problem? Please describe.**
Updates are currently handled by a reinstall of the application. This leads to excess usage of bandwidth and storage, at least temporarily. At the very least, portable games should be able to update *much* more efficiently, if we only download new or altered files.

**Describe the solution you'd like**
There are many options for such a situation. The one that comes to mind is hashing each file within the database, allowing a quick check between versions to yield the required files to transfer. No extra work would need to be done on the client side, just download the new and altered files, and place them in the game directory after ensuring the game has been stopped.

**Additional context**
This type of implementation would allow for the client to *verify game files* to repair an install. The client would "simply" hash all files within the games install folder, and send that information to the server. The server would check the database, and respond with a list of files that need to be deleted, as well as an archive of files that need to be extracted into the game directory, overwriting any corrupted or altered files in the process.

**Comment by Alfagun74** [comment]
This is too complex to implement it by itself but the idea may live on by utilizing the mechanism of #142
