### ISSUE TITLE
Analyze installers in an attempt to turn them into portable games

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-backend#139]
**Is your feature request related to a problem? Please describe.**
Game installers are often just self extracting archives with a few options and side jobs tacked on. Those side jobs are *very often* not required for the game to run.

Some examples:
- Option: Choose the install location
- Side job: Registry entries showing the game as installed for Windows
- Side job: Put an icon on the desktop
- Side job: Install dependencies
- Side job: Start menu shortcuts

**Describe the solution you'd like**
There exist packages that can analyze an installer. *This is not universally the case* of course, but for those installers that *can* be analyzed, the game can be turned into a live play game. The above examples (and likely others) could then be completely handled within GV. The benefit would be the ability to handle updates, and verification of game file integrity.

**Additional context**
Any game installers that cannot be analyzed can just remain as they are. It may be beneficial to require this to be optional, or require the admin to actively choose to do this with a game in the library.

**Comment by Alfagun74** [comment]
After a thorough evaluation, we have decided not to proceed with this feature request. The reasons for this decision are as follows:

Not Needed: Our platform already supports both installable and portable games, providing flexibility to our users. The install pipeline simplifies the installation process for both game types.

Complexity: Implementing this feature would be quite complex and resource-intensive. It would require significant development efforts, and the benefits it offers may not outweigh the development time and resources required.

If you want your install games to be portable just convert them yourself the way you think it make sense and then import the games into GV.

If you have any more suggestions or questions in the future, please don't hesitate to reach out. We value your feedback and are here to assist you.
