### ISSUE TITLE
LaunchBox integration/Plugin

### ISSUE THREAD

**Issue by PhuriousGeorge** [Phalcode/gamevault-backend#141]
**Is your feature request related to a problem? Please describe.**
Similar to #9, I'd like to see some form of integration/plugin to support LaunchBox

**Describe the solution you'd like**
Nothing specific to add here

**Describe alternatives you've considered**
Currently manually adding & managing games. Have used batch files and PowerShell scripts to do pretty much what GameVault doing.

**Additional context**
I'm pretty sure LB plugins are also coded in C#, similar to Playnite

**Comment by Alfagun74** [comment]
Appreciate the suggestion! We'll definitely consider looking into it at some point, but it would be great if a third-party developer could lend a hand here. 🥲

Check this link for more information: https://pluginapi.launchbox-app.com/
