### ISSUE TITLE
Ldap/oidc/forward auth authentication

### ISSUE THREAD

**Issue by lenaxia** [Phalcode/gamevault-backend#143]
**Is your feature request related to a problem? Please describe.**
This is a feature request to, at a minimum support ldap auth backend. As a user of gamevault, all my self hosted services share auth backends allowing my users to have a single login for all my services. 

**Describe the solution you'd like**
At a minimum, implement an "import from ldap" feature which imports users from ldap manually or on a schedule. More advanced, support oidc login through the client to the server.

**Comment by Alfagun74** [comment]
#6 is coming soon
