### ISSUE TITLE
Put swagger-ui

### ISSUE THREAD

**Issue by yodatak** [Phalcode/gamevault-backend#145]
It could good to have the swagger ui in the backend for dev facility

**Comment by Alfagun74** [comment]
its on /api/docs.

https://gamevau.lt/docs/advanced-usage/api-usage

**Comment by yodatak** [comment]
thanks but in the docs its  example.com/api/v1/docs and not  example.com/api/docs

**Comment by Alfagun74** [comment]
youre right, will fix
