### ISSUE TITLE
Additional User Management in Web UI

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-backend#147]
**Based on: Phalcode/gamevault-backend#150**

**Is your feature request related to a problem? Please describe.**
Relying on the client to manage users on the back end causes some issues, the largest of which in my mind is a reliance on access to a specific type of client (Windows at the moment.)

This also means that back end changes could result in the need to update the client, causing a large number of users to update "unnecessarily."

**Describe the solution you'd like**
One of two options makes the most sense. The first is a web ui, allowing user access/registration/approval to be completely controlled from the web (minus perhaps some "deep" changes such as admin password recovery.) This has the added benefit of being available on the vast majority of devices.

The second option would likely do well as a companion to the above, SSH. SSH access would not be as widespread as a web ui, but could allow for scripting, and changes that are "less safe" since SSH access typically means the user in question has more direct control over the machine in question.

**Describe alternatives you've considered**
Control through the client only, allows for easier development. However it locks any type of configuration down to only machines running Windows (and any future platforms added.) This seems like a bad overall solution, since many devices (phones for example) would need to have a client designed explicitly for them in order to allow "on the fly" config changes.

**Comment by Alfagun74** [comment]
I don't fully grasp your ticket.

Currently, configuring the server through the GameVault Windows app is not possible, so there is nothing to rely on.

The servers core configuration can only be changed via docker environment variables or the .env file. This ensures that only the one who runs the server can modify crucial settings, which is standard practice.

When you mentioned the issue on discord, I assumed you desired a WebUI for GameVault, enabling for example game browsing, profiles and so on. But you're asking for an explicit Configuration UI?

I fail to comprehend the SSH suggestion at all. 

@KairuByte do you even use the app yet? 😅

**Comment by KairuByte** [comment]
@Alfagun74 I've updated this ticket to target user management only. I will be creating a new ticket for initial setup and continued configuration of the back end through UI/SSH.

**Comment by Alfagun74** [comment]
Waits for #172

**Comment by Alfagun74** [comment]
Dies with https://github.com/Phalcode/gamevault-app/issues/284#issuecomment-1865310371
