### ISSUE TITLE
Server Configuration in Web UI

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-backend#150]
**Is your feature request related to a problem? Please describe.**
Relying on environment variables for configuration can cause some issues. The largest of which is the need to restart the entire back end when making a change. While these changes will likely not happen often, a restart of the back end will interrupt any ongoing processes such as downloads.

**Describe the solution you'd like**
The vast majority of configuration would best be served in a web interface for initial (and continued) setup. Most applications handle such things by having the first user created be the "super user," potentially requiring a custom string from the output of the service to ensure the user being created is *actually* the intended user, and not some random person who happened on the UI in the liminal state between spin-up and configuration.

**Describe alternatives you've considered**
SSH could likely be used, but UI typically beats out command line arguments when possible.

**Additional context**
Any config options set by environment variable should still be accessible as "read only" within the UI, with alt/hover text explaining that "this setting needs to be changed at the host level as it is set by environment variable." As such, *any* environment variables should override any configuration from within the application, including variables previously not present at the environment level. (Meaning, if you add an environment variable, it should still override the variable set within the back end.) *This should be noted within the UI* to ensure that the discrepancy is made obvious.

This would likely serve as a launching off point for Phalcode/gamevault-backend#147.

**Comment by lenaxia** [comment]
As an example, vaultwarden basically does a good job of this. Things set in env are visible but read only in the ui

**Comment by Alfagun74** [comment]
Waits for https://github.com/Phalcode/gamevault-backend/issues/172

**Comment by Alfagun74** [comment]
Died with https://github.com/Phalcode/gamevault-app/issues/284#issuecomment-1865310371
