### ISSUE TITLE
Email Verification System

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-backend#151]
**Is your feature request related to a problem? Please describe.**
If the email is ever needed to actually contact end users, such as to restore passwords, or alert on important changes, a legitimate email is obviously going to be required. Currently, the only verification is "does this look like an email?"

**Describe the solution you'd like**
Allow the admin to provide SMTP connection info, and turn on email verification. Verification would simply be a link emailed to the user, which verifies the account either through a direct link to the back end server in question, or through a protocol (Phalcode/gamevault-app#144)

**Describe alternatives you've considered**
You could spin up an SMTP server within docker, but this is a terrible idea as virtually any email sent out will be either spammed or dropped as spam.

**Comment by ChaosTherum** [comment]
I think it would also be worth making email optional. So just a config option during account creation, if that's even possible not sure how the db is structured.

**Comment by KairuByte** [comment]
This is a good point as well, if this is for family/home use there’s no need for email. Though that should likely be its own issue. 😜

**Comment by freitagdavid** [comment]
Very true.

**Comment by Alfagun74** [comment]
Thanks a lot for sending in this feature request. 

After looking into your request, we've decided not to go ahead with it for now. We do understand how crucial email verification is, but implementing SMTP functionality and email verification can be quite complex. It's a bit of an overkill for our user-friendly software, and it doesn't quite fit with our current priorities and technical setup. 

The Email field is not designed for password reset purposes right now. It's just so an admin can identify and contact you if necessary. If you provide bullshit data its your fault if your accounts locked and the admin can not reach you.

On a brighter note, we're considering making the email field optional with issue #157, so it won't be mandatory anyhow.
