### ISSUE TITLE
[Feature request] Edit/Re-request automatic image search for games

### ISSUE THREAD

**Issue by JoaGamo** [Phalcode/gamevault-backend#153]
**Is your feature request related to a problem? Please describe.**
 the problem is that sometimes game's images are not picked up correctly. For example, a game that released today, is properly named in my server according to the folder structure docs, but the image is from the same franchise but from many years ago. Saw this happen with other games being with the incorrect image (one somehow managed to obtain "nosferatu" wtf..?) doing the simple search manually for game box art I can see that the first results are the expected ones.

**Describe the solution you'd like**
This is not the first software that has problems like this, and it's normal.
On jellyfin, an opensource media-focused software, we can either choose from another metadata provider's image or upload our own. For Gamevault, it could be implemented the same way, after a wrong image is detected by a human, the admin can manually check the results of the simple image search and choose the proper one, or simply upload one themselves

**Describe alternatives you've considered**

**Additional context**

**Comment by Alfagun74** [comment]
[This already exists.](https://gamevau.lt/docs/client-docs/how-to-use#modifying-games:~:text=A%20popup%20will%20appear%2C%20where%20you%20can%20paste%20a%20URL%20for%20a%20different%20box%2Dart%20image)

**Comment by JoaGamo** [comment]
Somehow I missed it. Thank you!
