### ISSUE TITLE
Too much required information for accounts.

### ISSUE THREAD

**Issue by freitagdavid** [Phalcode/gamevault-backend#157]
**Is your feature request related to a problem? Please describe.**
Many of the registration options should be optional, either they could be completely optional, or a server admin could configure which should be optional and which should be required.

When creating an account on a friend or family member's server it seems pretty excessive to require first name, last name, and email. For something like this my expectation would be only requiring a username, and a password. Sure for a larger community it might make sense to require more data but for an instance with 3 or 4 people it seems overkill.

**Describe the solution you'd like**
Either make them optional, or add some sort of configuration to make them optional.

**Describe alternatives you've considered**
Typing gibberish for those fields.

---

Tasks:
For the Client:
- [x] Allow optional input for Email, First Name, and Last Name fields.

For the Server:
- [x] Set Email, First Name, and Last Name as nullable in the database.
- [x] Set up Configuration properties for mandatoriness of each of these fields.
- [x] Implement checks to ensure that only requests matching the configuration come through; deny requests that don't match the config.

**Comment by Alfagun74** [comment]
We plan to no longer require Email, First Name, and Last Name as mandatory fields. However, it's a good idea to provide this information voluntarily. It helps the server admin identify or contact you in case of any problems.

**Comment by Yelo420** [comment]
Implemented
