### ISSUE TITLE
Allow uploading of Trailers/Screenshots 

### ISSUE THREAD

**Issue by Wh1t3Rose** [Phalcode/gamevault-backend#158]
It would be nice if we could upload our own trailers/screenshots to our server and then allow our friends to view them in the library tab under that specific game.

We could either upload our own trailers or edit the game as an Admin and enter in a YouTube URL for that game within the GameVault Client.

**Comment by Alfagun74** [comment]
perhaps combinable with https://github.com/Phalcode/gamevault-backend/issues/149

**Comment by Alfagun74** [comment]
Waiting for #149

**Comment by Alfagun74** [comment]
Waiting for #258

**Comment by Alfagun74** [comment]
Screenshots are implemented.

**Comment by Alfagun74** [comment]
Attaching Youtube/Video Links for Trailers and Gameplays is now also possible. rest will be taken care of via  #161
