### ISSUE TITLE
Edit Game Details

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-backend#161]
**Is your feature request related to a problem? Please describe.**
I want to be able to edit bad looking, wrong, outdated or unsuiting game details as an EDITOR or ADMIN of a server. For example if i am chinese i want chinese descriptions.

**Describe the solution you'd like**
A GUI editor that allows me to change specific details of the game, like description, year of release etc.

**Describe alternatives you've considered**
Only API to edit games.

**Additional context**
RAWG Data must be saved in seperate rawg fields or tables like we do with title, release data etc. Or decoupled in another table entirely. Then being used and updated like a fallback if the user did not overwrite it.

## Functionalities needed in Client

- [x] Edit Age Rating
- [x] Edit Title
- [x] Edit Release Date
- [x] Edit Description
- [x] Edit Notes
- [x] Edit Average Playtime
- [X] Edit Cover Image
- [X] Edit Background Image
- [x] Edit Rating Score
- [x] Edit Early Access Flag
- [x] Edit Default Launch Parameters
- [x] Edit Default Launch Executable
- [x] Edit Default Installer Executable
- [x] Edit Screenshot URLs
- [x] Edit Trailer URLs
- [x] Edit Gameplay URLs
- [x] Edit Website URLs
- [x] Edit Publishers
- [x] Edit Developers
- [x] Edit Tags
- [x] Edit Genres
- [X] Remap Game for Provider
- [X] Unmap Game for Provider
- [X] Recache Game
- [x] Change Game Provider Priority

**Comment by jodoran** [comment]
Alternatively, maybe GameVault could use a specified .txt file in the directory of the game could be used instead of the description if there is one there?

**Comment by Alfagun74** [comment]
@jodoran #148

**Comment by Alfagun74** [comment]
Problem with the current implementation is that the RAWG Recache would just overwrite the user provided data as there is no way to check if it comes from the user or from rawg.

**Comment by Alfagun74** [comment]
We would need to save the user provided data differently, maybe in another table

**Comment by Alfagun74** [comment]
Needs https://github.com/Phalcode/gamevault-backend/issues/258 first.

**Comment by Alfagun74** [comment]
Implemented on Server-Side

**Comment by Yelo420** [comment]
Implemented
