### ISSUE TITLE
LGOGDownloader Support

### ISSUE THREAD

**Issue by mautobu** [Phalcode/gamevault-backend#162]
**Is your feature request related to a problem? Please describe.**
Content ingestion is clunky. Lots of manual processes.

**Describe the solution you'd like**
I'd like to see a script or gui way to directly ingest and query install files and metadata. Could use https://github.com/Sude-/lgogdownloader to do most of the heavy lifting.

**Comment by Alfagun74** [comment]
Thanks for the suggestion! However, we don't plan to directly integrate LGOGDownloader support into GameVault right now.

This could be a great chance for a third-party developer to step in and create a script. This script would take the LGOGDownloader output and convert it into the GameVault format, making it easy to import into your /files volume.
