### ISSUE TITLE
Make GameVault compatible with Heroic Game Launcher

### ISSUE THREAD

**Issue by ncmtl** [Phalcode/gamevault-backend#166]
**Is your feature request related to a problem? Please describe.**

I currently own a Steam Deck and installed the great alternative game downloader/launcher Heroic Game Launcher (https://heroicgameslauncher.com/). I can connect to gog.com and Epic Game Store, download and install windows game on my device. Yet I cannot install easily my own game library that stays on my nas. I need to sideload the game (usb or cumbersome file browser) and add it manually to Heroic Game Launcher. 

**Describe the solution you'd like**

That would be awesome if I could set up my own game server and use Heroic as a client. I believe GameVault is the game server I am looking for and Heroic is the client. For that you need the two apps to communicate through a public API.

**Describe alternatives you've considered**

There is no alternative for this use case as I know.

**Additional context**

Obviously before starting such a project there is a need to contact devs from Heroic Game Launcher to establish an API. I've looked at their code and I think there is some dev to do from their side too.
If done right GameVault will probably very popular amongst Steam Deck users !

Thanks for taking the time to read my feature request :)

**Comment by Alfagun74** [comment]
After checking out heroic, I couldn't find any plugin system or anything similar. So, it looks like you'll have to create a ticket on Heroic's Issue tracker, titled "Make Heroic Game Launcher compatible with GameVault." 😁

However, we can pave a way for them to do it by taking care of https://github.com/Phalcode/gamevault-app/issues/144 first. So maybe wait until thats done.

Feel Free to reopen if you know there is a plugin system we can build on.

**Comment by Alfagun74** [comment]
I'll send them an email from our company asking if they're interested in collaborating.
