### ISSUE TITLE
"Password is not strong enough" is not an easily actionable error message.

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-backend#174]
**Describe the bug**
"Password is not strong enough" is not an easily actionable error message.

**To Reproduce**
Attempt to create a user account with the password 12345678

**Expected behavior**
Password requirements be shown to explain to the user what needs to change with their password to be accepted.

**Additional context**
Not 100% certain this is server side, but I believe the error message comes from the server.

**Comment by Alfagun74** [comment]
This originates from here https://github.com/typestack/class-validator/blob/c3d561c469a09b6620fc8f96cade888b9087dd16/src/decorator/string/IsStrongPassword.ts#L37

Fixed in the next GV version.
