### ISSUE TITLE
Fail2Ban and GameVault

### ISSUE THREAD

**Issue by 60plus** [Phalcode/gamevault-backend#175]
Hello.
Anyone can help me setup fail2ban for GameVault ?

**Comment by Alfagun74** [comment]
I personally don't use Fail2Ban but if i understand it correctly, in theory you theoretically could do the following:

- 1. Enable Log Files and map a volume to the /logs folder
```ENV
SERVER_LOG_FILES_ENABLED=true
```
- 2. Failed Authentication Attempts will look like this:
```bash
info:    ┏ [17/Aug/2023:20:25:47 +0000] Username @ Address - GET /api/v1/users/me -> 401 - 28.231 ms - 112 - 'GameVault/1.3.0'
```

- 3. Now make filter file for fail2ban:
```bash
sudo nano /etc/fail2ban/filter.d/gamevault-filter.conf
```

put in something like:
```bash
[Definition]
failregex = ^\[:date[^\]]+\] [^@]+@ <ADDR> - .* -> 401 - .*$
```

NOTE: I haven't tested this regex you may need to tinker around a bit using
```bash
fail2ban-regex /wherever/logs/gamevault-backend.log /etc/fail2ban/filter.d/gamevault-filter.conf
```

- 4. Next edit your Jail File
```bash
sudo nano /etc/fail2ban/jail.local
```

Add this block (configure as you like)
[gamevault]
enabled = true
filter = gamevault-filter
logpath = /wherever/gamevault/logs/*.log
maxretry = 10
findtime = 3600
bantime = 3600

- 5. Restart or reload the fail2ban service for the changes to take effect.
```bash
sudo systemctl restart fail2ban
```

- 6. Now do a bunch of unauthenticated requests and check if your jail is working
```bash
sudo fail2ban-client status gamevault
```

I hope this works for you. Make sure to tell me if you have found a reasonable configuration and regex for this.

Be aware the 401 throws on every unauthenticated request, which can happen fast and be annoying so set the max-retry a bit higher.

Also Kudos to [this StackOverflow Answer](https://stackoverflow.com/a/69575369/14570696)

**Comment by Alfagun74** [comment]
I've added a Guide for this to the Documentation: https://gamevau.lt/docs/advanced-usage/fail2ban-gamevault-guide

**Comment by 60plus** [comment]
Thank You.
