### ISSUE TITLE
The game title should be the only necessary file identifier

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-backend#180]
**Is your feature request related to a problem? Please describe.**
Currently GameVault needs at least the game title and the release year to add a game to the Vault. I dont like the need to research all game release years.

**Describe the solution you'd like**
The Title should be enough to match a game in RAWG in the most cases. In cases where there are two games that share the same name, you can still specify it.

**Comment by AJV20** [comment]
I like the way media servers like Plex and Emby do it. If the wrong movie is selected there’s an option in the UI to change the selection![image](https://github.com/Phalcode/gamevault-backend/assets/24819659/d320ed96-33b2-4633-8b2d-ea039723b74b)![image](https://github.com/Phalcode/gamevault-backend/assets/24819659/9a9de285-da10-40df-8f49-533f605588ba)

**Comment by Alfagun74** [comment]
@AJV20 we already have this feature:
https://gamevau.lt/docs/client-docs/how-to-use#modifying-games
