### ISSUE TITLE
Redirect non-existant WebUI to the Microsoft Store Page of GameVault for now

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-backend#182]
**Is your feature request related to a problem? Please describe.**
I'm facing GV to the public internet on a subdomain, I don't really feel that https://gamevault.example.com/ should display the default "good job this is gamevault" page.

**Describe the solution you'd like**
Short term, redirect to the microsoft store. Long term, I believe there is an intent for a web UI.

**Describe alternatives you've considered**
It could be left as is, or manually handled through any number of situations, but there really isnt a point to this screen at all.

**Comment by KairuByte** [comment]
Note: If anyone else wants to achieve the above, and is using nginx, this should work without messing up your api calls:
```txt
location = / {  
    return 302 https://apps.microsoft.com/store/detail/gamevault/9PCKDV76GL75;
}```

**Comment by Alfagun74** [comment]
interesting idea, i will cast a poll

**Comment by Alfagun74** [comment]
The Poll was inconclusive.

![image](https://github.com/Phalcode/gamevault-backend/assets/22225051/d394d2f8-1eaa-47e2-b62c-3b9156a5923e)

I will cast another one and let it run for 7 days instead of 2.

**Comment by Alfagun74** [comment]
The Council has spoken.
![image](https://github.com/Phalcode/gamevault-backend/assets/22225051/9ccd5ccd-c781-433e-9dfb-f5736094d422)

**Comment by Alfagun74** [comment]
Psst.. @KairuByte 🤫 

Don't tell the council but i secretly at least implemented a Link to the Microsoft Store:

![image](https://github.com/Phalcode/gamevault-backend/assets/22225051/5afaae18-ca20-4dac-9db8-a120cb6a314d)
 
Hope this satisfies you :)
