### ISSUE TITLE
Documentation for installing this software

### ISSUE THREAD

**Issue by parski** [Phalcode/gamevault-backend#183]
**Is your feature request related to a problem? Please describe.**
The documentation lists three ways of installing this software but all of them relies on heavily integrating some sort of container monolith (in this case, variations of Docker) into your system. This is not always possible or desireable.

**Describe the solution you'd like**
Documentation for how to install the software not relying on containers. Just normal dependencies, setting up a user and maybe setting up tables in a database. I don't know what your software needs, I don't speak dockercomposeyaml.

**Describe alternatives you've considered**
Creating a virtual machine, installing Linux and Docker in that, jumping through burning hoops while doing flips and landing in the middle of the circus to standing ovations. 

**Additional context**
None of the deployment options work on the BSDs.

**Comment by Alfagun74** [comment]
I see you're not a fan of containers, but i really do recommend them. However i will try to add docs for how to build and run this from source.

**Comment by parski** [comment]
I love containers. However, this (and many other projects) cater heavily to one specific container vendor. I like using FreeBSD jails to containerize. On Linux machines I like LXC or just chroot. Lots of people use Podman and others like to virtualize. I also recommend containers but I think there should at least be an option to do a bare metal install if people use different container engines or just want to keep things in the host.

**Comment by Alfagun74** [comment]
By the way, for now, since there are no specific instructions yet, please just follow the Dockerfile instructions on your own machine. It's not really magic; it's straightforward. You can find the instructions [here](https://github.com/Phalcode/gamevault-backend/blob/9bdef059e884ff0f8258c43fe44075ed51c68b07/Dockerfile).

**Comment by Alfagun74** [comment]
will soon be on the live site!
