### ISSUE TITLE
Humble Bundle Downloader Support

### ISSUE THREAD

**Issue by UnholyVision** [Phalcode/gamevault-backend#184]
**Describe the solution you'd like**
I would like to see GameVault be able to pick up on the folder names and structures these use. This might be a bit of a ask, but when you mass download with these (specially lgogdownloader) there are many things downloaded besides just the game. GameVault is suppose to be for DRM-Free games and it would be nice to see it support the folder structures of say "dlc", "patches", and "extras" if possible from GOG games.

**Describe alternatives you've considered**
Alternative, would maybe be implement them directly if possible. Though, that is a tall ask to piggyback off these pieces of software.

**Additional context**
Since these two programs can repair broken installers, get patches, and DLC it's kind of a pain restructuring if you want to run another repair or check for DLC or patches on your collection.

**Comment by Alfagun74** [comment]
Thanks for the suggestion! However, we don't plan to directly integrate Humble Bundle Downloader support into GameVault right now.

This could be a great chance for a third-party developer to step in and create a script. This script would take the HBD output and convert it into the GameVault format, making it easy to import into your /files volume.
