### ISSUE TITLE
Swagger yaml and json generated api don't have basic auth so openapi generation failed to genered good code

### ISSUE THREAD

**Issue by yodatak** [Phalcode/gamevault-backend#186]
npx @openapitools/openapi-generator-cli generate -i https://demo.gamevau.lt/api/docs-yaml -g rust -o /tmp/test2/

and we don't get good code because of lack of 
https://swagger.io/docs/specification/authentication/
 
exemple 

    paths:
      /something:
        get:
          security:
            - basicAuth: []
    basicAuth:     # <-- arbitrary name for the security scheme
      type: http
      scheme: basic

**Comment by yodatak** [comment]
I think it come from
https://docs.nestjs.com/openapi/security

maybe it lack 
@ApiBasicAuth()

near 
@Controller("games")

**Comment by yodatak** [comment]
i got some error in using the api in rust is it a database issue ?
Error sending message: error in serde: missing field `games` at line 52 column 5

**Comment by Alfagun74** [comment]
fixed in v5.0.0, i dont know where the error you posted comes from
