### ISSUE TITLE
Refactor /api/v1/rawg/search

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-backend#187]
**Is your feature request related to a problem? Please describe.**
A direct from RAWG API call takes less than a second, while a call to the above can take upwards of 30 seconds. This can likely be optimized considerably.

**Describe the solution you'd like**
Refactor/optimize the API call.

**Comment by Alfagun74** [comment]
Ive been able to reduce the Rawg Search Calls from about 20-30 secs to 1-4 secs. Comes in in 6.0.0:

Significant improvements have been made to the RAWG Search API, making it about 5 times faster and reducing its data consumption. [#187](https://github.com/Phalcode/gamevault-backend/issues/187)
  - Previously, search results unintentionally created numerous tags, genres, developers, and stores in your databases, and even images on your filesystem.
  - This is no longer the case. The RAWG Search now provides only essential game information for identification and remapping.
