### ISSUE TITLE
Require an opt-in environment variable for API documentation

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-backend#188]
**Is your feature request related to a problem? Please describe.**
Serving API documentation isn't always desirable. While not necessarily a security concern, it's usually best practice to only show it when the admin/owner has explicitly enabled it.

**Describe the solution you'd like**
An opt-in environment variable such as SERVER_API_DOCS would be ideal.

**Describe alternatives you've considered**
Killing off the docs with a reverse proxy, but this is a terrible idea.

**Comment by Alfagun74** [comment]
implemented `SERVER_API_DOCS_ENABLED` in 5.0.0
