### ISSUE TITLE
Swagger UI "Try it out" appears to be polling a test database

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-backend#189]
**Describe the bug**
When you run a "try it out" API call in Swagger UI, you get what appears to be test data. In the example below, I am getting Grand Theft Auto, which is not a game in my library.

**To Reproduce**
1. Go to Swagger UI `/api/docs`
2. Log in
3. Pick an API call (I chose `/api/v1/games`
4. Run the call

**Expected behavior**
Proper data, from the "production" database.

**Comment by Alfagun74** [comment]
There is no test database. 
It works perfectly fine.

![Image](https://github.com/Phalcode/gamevault-backend/assets/22225051/2703d3d2-b6ab-47c1-b065-6c83027dd6e2)

Make sure to set the server and authentication correctly at the top and actually execute the request instead of just checking the example data in the YAML.

**Comment by Alfagun74** [comment]
GTA V is indeed my example data, i dont think your request works at all:


![Image](https://github.com/Phalcode/gamevault-backend/assets/22225051/add68821-6397-40fc-8909-6df9fe24e95e)

**Comment by KairuByte** [comment]
Hrm, I suppose I was missing the error between the two in this image, so the title should be "Try it now does not work" as no matter my inputs, this is the result:

![image](https://github.com/Phalcode/gamevault-backend/assets/393806/55123369-ec24-48b2-85f2-787e078ca6aa)

**Comment by Alfagun74** [comment]
Honestly, this could be a bug to report on https://github.com/swagger-api/swagger-ui. I can't control this interface a lot, so I'm not sure why it wouldn't work on an iPhone. It might be related to [this browser or CORS issue](https://github.com/swagger-api/swagger-ui/issues/1888). Unfortunately, I don't have the option to configure `enableCors` in https://github.com/nestjs/swagger either. I don't think disabling "Try it Out" is necessary, but I can do that as well if needed.
