### ISSUE TITLE
Matching issues

### ISSUE THREAD

**Issue by strese** [Phalcode/gamevault-backend#191]
**Describe the bug**
I am experiencing matching issues. Games being matched to wrong games and when I try matching the game manually by pressing the pencil icon and searching for the game, the game doesn't show up as a search result. I'm seeing this with several games. The majority of the games I have works just fine, but a few doesn't. This game is one example.

**To Reproduce**
1. Go to pencil
2. Click on Rawg game
3. Search for game
4. Wrong result

**Expected behavior**
As far as I understand it, as long as I search for a game with the same spelling as at RAWG, the game should show up as a search result.

**Screenshots**
In the gamevault client
![In gamevault client](https://github.com/Phalcode/gamevault-backend/assets/13396115/32612b25-35db-4018-b4eb-0270ae7b26df)

The actual file name
![The actual file name](https://github.com/Phalcode/gamevault-backend/assets/13396115/439fe447-778f-4539-8f4d-bcbc3baa53b2)

The game at RAWG
![The game at RAWG](https://github.com/Phalcode/gamevault-backend/assets/13396115/3084df16-cedd-4bff-886f-ff7aecd34257)

**Additional context**
I'm not sure if I'm missing something critical or if there is a bug. Any help would be very appreciated!

**Comment by Alfagun74** [comment]
itch.io exclusive games are excluded from search to make the search more accurate. To Enable itch.io exclusive Games you can try to empty the `RAWG_API_EXCLUDE_STORES` env var like this `RAWG_API_EXCLUDE_STORES=` in backend v5.0.0 or higher.

**Comment by strese** [comment]
That worked perfectly. Thank you!!

**Comment by Alfagun74** [comment]
Awesome, thanks for testing. You know where our tip jar is if you are satisfied and have some spare dollars. 😊
