### ISSUE TITLE
Flag to prevent Game to be RAWG indexed

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-backend#194]
**Is your feature request related to a problem? Please describe.**
Sometimes games arent games. Similar to Phalcode/gamevault-app#237, if I want to have a patch file in place that isn't actually a game, things get confusing when the game mapper decides that "Cool Game Patch Number 123 for version 122" is actually "Cool Game", grabbing the description and images for the original game and putting them alongside the original.

**Describe the solution you'd like**
A flag that prevents any game mapping from taking place. Perhaps `(DNM)` for "Do Not Map"?

**Additional context**
My original use case will be wiped out once "extra file" support is added to GV, but I'm sure other will have a use for it for things that arent actually public such as an unreleased indie game.

**Comment by Alfagun74** [comment]
This is not supported (but we're working on it).

To put it humorously, it's a bit like tossing cabbage into a broccoli sorting machine and asking the manufacturer not to slice the cabbage in half. 😂

If you really like and need the extra files ticket and urgency is a concern, you can consider liking it or placing a motivational bounty donation to make us work on it ASAP.

**Comment by Alfagun74** [comment]
This is not supported (but we're working on it).

To put it humorously, it's a bit like tossing cabbage into a broccoli sorting machine and asking the manufacturer not to slice the cabbage in half. 😂

If you really like and need the extra files ticket and urgency is a concern, you can consider liking it or placing a motivational bounty donation to make us work on it ASAP.

I legitimately don't see a lot of users needing the case for the unpublished indie game example.

**Comment by Alfagun74** [comment]
Implemented `(NC)` (NoCache) Flag in v6.0.0
