### ISSUE TITLE
API admin endpoint to view download status

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-backend#199]
**Is your feature request related to a problem? Please describe.**
If I need to restart a PC at some point, for an update of the host or GV itself, it would be nice to be able to check if there are any users currently downloading.

**Describe the solution you'd like**
An admin API endpoint that lists current downloads, their speeds, their progress, and their estimated time left (based on `([total size] - [total downloaded]) / [current speed]`)

**Describe alternatives you've considered**
You can technically comb through the logs if they are set to show the level necessary, but this isn't really a good workaround.

**Comment by Alfagun74** [comment]
We'll introduce this feature step by step, starting with an MVP (Minimum Viable Product). Initially, there will be an API indicating the presence of active downloads and an exclamation mark in the admin panel to signal ongoing server downloads. Additional features such as progress tracking, ETA, speed, and more details may be added in subsequent phases.

**Comment by Alfagun74** [comment]
After discussing further within our team, we're reconsidering whether this issue will still be relevant if we integrate feature #14 (pausable downloads). If downloads can seamlessly resume where they left off after a restart, we shouldn't encounter this problem, similar to the smooth experience provided by Steam. Would this not address the ticket for you? @KairuByte

**Comment by KairuByte** [comment]
That was indeed the use case, and resumable downloads cover the issue nicely.
