### ISSUE TITLE
Custom server GameType or more filters

### ISSUE THREAD

**Issue by JamesDAdams** [Phalcode/gamevault-backend#212]
**Is your feature request related to a problem? Please describe.**
I want a GameType for APK, IPA, SOFTWARE...

**Describe the solution you'd like**
**Solution 2 :** Each GameVault-backend can add custom GameType in files name and the backend send to the client the custom GameType list.

That would be very grate to have 3 filter : 

Type :
	- Game
	- SoftWare
	- ...

Platforme :
	- Windows
	- MACOS
	- Android
	- IOS
	- PS4
	- Switch
	- ...

Installation :
	- Installer
	- Portable
	- ...

### If a take the **Naming Convention for Games** in the doc and add new filters : 

| Part         | Description                                                                                                             | Example Value(s)                      | Required? |
|--------------|-------------------------------------------------------------------------------------------------------------------------|---------------------------------------|-----------|
| Title        | The name of the game                                                                                                    | Far Cry 6, HITMAN 3                   | Yes       |
| Version      | An optional version tag that must begin with a lowercase v                                                              | (v1.0), (v1.224) , N/A                | No        |
| EarlyAccess  | An optional tag that indicates whether the game is in Early Access                                                      | (EA), N/A                             | No        |
| GameType     | Override for the games type. See here.                                                                                  | (W_P), (W_S), ... , N/A               | No        |
| NoCache      | An optional "NO CACHE"-flag that prevents the server searching for this game on external videogame databases like RAWG. | (NC), N/A                             | No        |
| ReleaseYear  | The year of the game's release, for accurate detection                                                                  | (2021), (2019), N/A                   | No        |
| Platforme    | The platform compatible for the installation                                                                            | (p_WIN, p_MAC, p_MACM1, p_IOS, p_APK) | No        |
| Installation | The installation methode                                                                                                | (i_P, i_S)                            | No        |
| Type         | Type of soft                                                                                                            | (t_game, t_soft)                      | No        |

**Describe alternatives you've considered**
No alternative considered

**Additional context**
No additional context

**Comment by Alfagun74** [comment]
Thank you for bringing up this point. While GameVault currently focuses primarily on videogames, we acknowledge that it's technically possible to use it for software and apps. However, it's not the intended use at this moment. We appreciate your input and will certainly consider it for future enhancements.

Regarding the organization of game types by platforms, our current plan is to assign a specific game type to each platform instead of splitting The Game-Type by Platforms.

Your contribution is valuable, and we're grateful for your engagement with GameVault. If you have any more suggestions or questions, feel free to share them.
