### ISSUE TITLE
Allow RAWG search without stores parameter

### ISSUE THREAD

**Issue by drustan-hawk** [Phalcode/gamevault-backend#239]
**Is your feature request related to a problem? Please describe.**
Some games don't have a store assigned to them on rawg.io. This causes them to never be returned when searched since the `stores` parameter is always present in the query.

**Describe the solution you'd like**
Some way to search via the rawg integration without the stores parameter. Perhaps, if the __RAWG_API_INCLUDED_STORES__ environmental variable is an empty string, the parameter could be excluded in queries.

**Describe alternatives you've considered**
~

**Additional context**
I made some requests to the _https://api.rawg.io/api/games_ endpoint with and without the `stores` parameters to verify. `stores` have to be excluded entirely.

With that said, I only briefly looked at the code and could be wrong about the reason certain games aren't returned.

---

@Alfagun74 To Do:

**Server**
For Automapping: 
- [X] offer the admin to enter the store "0" (All Stores) globally into the ``RAWG_API_INCLUDED_STORES`` configuration, which searches RAWG completely without the "stores" parameter   
- [X] offer another setting called ``RAWG_API_INCLUDED_PLATFORMS`` that does the same for platforms
- [X] document all store and platform ids in documentation

Additionally if admins want to override this for a single game like in this case:
- [ ]  Enhance Rawg Search API, so it accepts paremeter for "store" and "platform", to use for the search.

**Client**
- [ ] Offer dropdowns for "Platform" and "Stores" next to the remap search

**Comment by Alfagun74** [comment]
Can you give me some examples of games you can't find?

**Comment by drustan-hawk** [comment]
Sure. What a Legend!, fair warning though, it's nsfw.

**Comment by Alfagun74** [comment]
Thanks for the warning. Was just about to look this up next to my wife. Decided to check it out tomorrow instead. :)

**Comment by drustan-hawk** [comment]
Heh, that could've been fun! But anyway, thanks for a fast reply. Have a good New Year's 😃

**Comment by Alfagun74** [comment]
I find this API quite frustrating. 

The 'exclude_stores' parameter filters out games that have itch.io listed anywhere in the array. 
On the other hand, the 'include_stores' parameter filter out games that are not associated with any store. 

I simply want a way to exclude those annoying itch.io asset flips.

Let me see what i can do.

**Comment by Alfagun74** [comment]
Hey @drustan-hawk, i have thought about this frustrating issue for quite a while and have come up with a solution,

**Server**
For Automapping: 
- [ ] offer the admin to enter the store "0" (All Stores) globally into the ``RAWG_API_INCLUDED_STORES`` configuration, which searches RAWG completely without the "stores" parameter   

Additionally if admins want to override this for a single game like in this case:
- [ ]  Enhance Rawg Search API, so it accepts paremeter for "store" and "platform", to use for the search.

**Client**
- [ ] Offer dropdowns for "Platform" and "Stores" next to the remap search

How do you like this idea?

**Comment by drustan-hawk** [comment]
Hi!

I think it sounds great! It would definitively solve the issue I encountered. For the client dropdown, would the "All Stores" option be available?

**Comment by Alfagun74** [comment]
absolutely, that would be the default

**Comment by Alfagun74** [comment]
Design Mockup:
![Game Settings Rawg (w Filters)](https://github.com/Phalcode/gamevault-backend/assets/22225051/553da1d6-c5a8-4236-ad76-347dc0e43c70)

**Comment by drustan-hawk** [comment]
Looks good! Looking forward to it 😄

**Comment by Alfagun74** [comment]
now that i know [how many platforms are supported](https://gamevau.lt/docs/server-docs/indexing-and-metadata#rawg-platforms) we should maybe use a more similar control to the "Game Type Filter" in library, but only with one selectable platform/store:


![Image](https://github.com/Phalcode/gamevault-backend/assets/22225051/a13d902e-490a-481a-a7ee-0da656b8f85d)

**Comment by Alfagun74** [comment]
We will probably not continue to support RAWG due to #258, so this ticket counts as completed now.
