### ISSUE TITLE
Auto update box art when manually remapping a game match

### ISSUE THREAD

**Issue by Jmatt110** [Phalcode/gamevault-backend#240]
When remapping a game due to a failure to map correctly, the Background image is downloaded correctly, but the box art does not automatically update to the new mapping.

Eg. Gamevault maps a game as Solitaire and downloads box art for it but no background image. Manually fix the mapping via RAWG function to Minesweeper results in the correct image being downloaded for Minesweeper, however the original (incorrect) Solitaire box art is not automatically updated to Minesweeper's.

**Comment by Alfagun74** [comment]
Fixed, along with a lot of other shit i stumbled upon. :)
