### ISSUE TITLE
Allow to hard-delete users after soft-deleting them.

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-backend#245]
There should be an irreversible option to permanently delete a user after soft-deleting him.

We need to:
- [ ] Implement that a second DELETE on a user permanently deletes him.
- [ ] Show that somewhat clear in the UI, maybe using https://github.com/Phalcode/gamevault-app/issues/250#issue-1911464860

**Comment by Alfagun74** [comment]
I do not require this anymore, as i can hide deleted entries and that totally fixes my original issue.

@wiseoxejah & @blandmann, dont hesitate to comment if you still require this.

**Comment by wiseoxejah** [comment]
> I do not require this anymore, as i can hide deleted entries and that totally fixes my original issue.
> 
> @wiseoxejah & @blandmann, dont hesitate to comment if you still require this.

I don't need it anymore. I do think it is a useful feature though. Maybe something to return to in the distant future. All good for now though. Thanks!
