### ISSUE TITLE
Encrypted (password protected) archive support

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-backend#250]
**Is your feature request related to a problem? Please describe.**
Sometimes I don't want a file to be immediately readable by the system I am hosting the files on. Be it me not wanting a VPS to dig through and see I'm hosting game files for download, or me not wanting my data to be accessible by a third party without my permission.

**Describe the solution you'd like**
Support encryption. Allow the setting of an "archive password" to keep the files from being casually opened, looked into, or taken from.

**Comment by KairuByte** [comment]
My initial envisioning was to keep data at least somewhat secure in the case of the transferred zip being nabbed. But I suppose this could work for other things as well. With that in mind, I think I'm a fan of the combo option, try a default that is shared with the client by the server, and if that doesn't work *then* prompt.

**Comment by Alfagun74** [comment]
thanks for the prompt response, we will see what we can do :)

**Comment by Yelo420** [comment]
Implemented including the default password setting.

User will be asked for the password in a new password prompt , if the archive is password protected.

Here the edgecase logic:
Is Encryped? ->YES: Has default extraction password set? ->YES: Default password failed?->YES: **Asking for password with the new password promt**-> is given password correct ->NO: Status error. "Wrong password"

**Comment by Astro1247** [comment]
Hi! I found this feature request while searching how to set a per-game password server side to unpack game and it seems that its impossible right now, only whole system default one password. Can this feature please be extended to be able to set per-game password to unpack, to specify it as admin in game fields somewhere. It would be really cool!

**Comment by Alfagun74** [comment]
> Hi! I found this feature request while searching how to set a per-game password server side to unpack game and it seems that its impossible right now, only whole system default one password. Can this feature please be extended to be able to set per-game password to unpack, to specify it as admin in game fields somewhere. It would be really cool!

Of course! Would you mind to create another feature request for that @Astro1247?

We will take a look at it once we have #148 in place.

**Comment by Astro1247** [comment]
> > Hi! I found this feature request while searching how to set a per-game password server side to unpack game and it seems that its impossible right now, only whole system default one password. Can this feature please be extended to be able to set per-game password to unpack, to specify it as admin in game fields somewhere. It would be really cool!
> 
> Of course! Would you mind to create another feature request for that [@Astro1247](https://github.com/Astro1247)?
> 
> We will take a look at it once we have [#148](https://github.com/Phalcode/gamevault-backend/issues/148) in place.

Awesome! Thank you, I've created #350 describing this request. It would be cool.
