### ISSUE TITLE
Return an option to scan the files folder every x minutes.

### ISSUE THREAD

**Issue by ozhound** [Phalcode/gamevault-backend#251]
After troubleshooting with KairuByte, it seems that the feature to let the system receive updates from container when changes to the file system occur is broken in my installation. 

1. Proxmox HV with Docket LCX and Gamevault installed
2. files directory is located on the host ZFS file system and accessed via an NFS Share mapped to the docker container

This setup, for whatever reason, isnt refreshing the database and a manual re-index needs to be triggered to add newly added games.

Thanks

**Comment by Alfagun74** [comment]
The old alorithm has already been reimplemented and will come with the next update. https://github.com/Phalcode/gamevault-backend/issues/246
