### ISSUE TITLE
Steam API for metadata

### ISSUE THREAD

**Issue by Toylerrr** [Phalcode/gamevault-backend#252]
Look into using the Steam API directly for more comprehensive game data. This includes fetching Steam App IDs, game names, images (box art, screenshots), prices, and metascores.

Samples:

https://api.steampowered.com/ISteamApps/GetAppList/v0002/?format=json

https://store.steampowered.com/api/appdetails?appids=10

https://steamcdn-a.akamaihd.net/steam/apps/<APP_ID>/library_600x900_2x.jpg

**Comment by Alfagun74** [comment]
awesome. should be the default in my opinion.

Must be modular etc tho.

**Comment by Alfagun74** [comment]
Needs https://github.com/Phalcode/gamevault-backend/issues/258 first.

**Comment by Alfagun74** [comment]
Maybe this could be the first metadata provider to be implemented as a plugin in #140

**Comment by Alfagun74** [comment]
https://github.com/Phalcode/rawg-to-steam-redirect was born
