### ISSUE TITLE
[FEATURE] ROMs game type/integration

### ISSUE THREAD

**Issue by MegaShinySnivy** [Phalcode/gamevault-backend#260]
**Is your feature request related to a problem? Please describe.**
It is not!

**Describe the solution you'd like**
A ROMs game type or integration. This could be general or per-system type. Ideally it would just download the file to a folder the user defines for that ROM type (3ds, wii, etc), and if save-game (or even save-state?) syncing is enabled, that respective folder as well. 

**Describe alternatives you've considered**
I don't believe there is an alternative to be considered. 

**Additional context**
There does not seem to be a 'single' file game option, which this could be extended to support. In essence--write once, use for whatever type needed.

**Comment by Alfagun74** [comment]
Thanks for reaching out. This is a duplicate. We plan to support this within https://github.com/Phalcode/gamevault-app/issues/269
