### ISSUE TITLE
404 when trying to download a game

### ISSUE THREAD

**Issue by Kudjo-Grand** [Phalcode/gamevault-backend#269]
[f78ec576f1cf484739afc2a793e0aa1aba0bde558294b2c5bd4c3730eb40ea9c-json.log](https://github.com/Phalcode/gamevault-backend/files/14842670/f78ec576f1cf484739afc2a793e0aa1aba0bde558294b2c5bd4c3730eb40ea9c-json.log)

Here are the full logs after a restart and attempting to download a title that is in a subdirectory.

Let me know if you need more information.

**Comment by Alfagun74** [comment]
I changes some stuff on the file indexer and messed up file paths, will be fixed in v11.0.1
