### ISSUE TITLE
[Request] Simplified game install

### ISSUE THREAD

**Issue by LoganJFisher** [Phalcode/gamevault-backend#273]
**Is your feature request related to a problem? Please describe.**
If I want to download and install a game onto my PC from my server, I must download, extract, and then install the game as three separate functions. This adds, what I believe to be, unnecessary complication to the user experience

**Describe the solution you'd like**
I understand that some users may, for whatever reason, want such granular control, but I would find it far more convenient to have a single download button that does all three. That is, a single click to download, extract, and install the game such that it then appears under the list of installed games with no further user interaction needed beyond that single click (not unlike how how game launchers like Steam work).

**Describe alternatives you've considered**
I've not considered any alternatives.

**Additional context**
![dWnZi1w](https://github.com/Phalcode/gamevault-backend/assets/63993409/20d7a224-6003-434d-b02f-a04dc3077d2c)
![MujTPDl](https://github.com/Phalcode/gamevault-backend/assets/63993409/6a020983-b04c-4e37-81fa-430b5361c3bc)
![ESX6FUK](https://github.com/Phalcode/gamevault-backend/assets/63993409/3b8f8634-834b-4516-8890-569b6b899ce3)

**Comment by LoganJFisher** [comment]
Ah, I just found the auto-extract games toggle. So partial-solution.

**Comment by Alfagun74** [comment]
this could work perfectly fine for portable games but setup.exe games that require a manual installation process unfortunately cannot be automated like this. Nevertheless a ticket to implment auto-install similar to auto-extract already exists in https://github.com/Phalcode/gamevault-app/issues/259.

It would be nice if you could note there that you would also require both functions to be on by default.
