### ISSUE TITLE
[Bug] Can not upload images

### ISSUE THREAD

**Issue by LoganJFisher** [Phalcode/gamevault-backend#274]
**Describe the bug**
I can not upload images (e.g. box art or profile photo). Neither URL nor uploading from a local file works.

**To Reproduce**
1. Go to any location where an image could be uploaded
2. Attempt to upload an image by either means

**Expected behavior**
Image should upload successfully

**Screenshots**
![TDwE5Y1](https://github.com/Phalcode/gamevault-backend/assets/63993409/b3387e27-5ead-4729-bdf6-51f27841a571)
![mROXSmu](https://github.com/Phalcode/gamevault-backend/assets/63993409/4e67618b-e788-42e4-8802-215df7c158da)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home 64-bit
 - Version: Build 22621

**Comment by Alfagun74** [comment]
[Most probably it is due to a permissions error on your images volume](https://gamevau.lt/docs/troubleshooting/#server-fails-to-save-images--create-sqlite-database--index-games-or-throws-a-permissions-denied--no-permission--eacces-error)

**Comment by LoganJFisher** [comment]
Solved in discussion #272
