### ISSUE TITLE
Game sorting error with numbers in the name. 

### ISSUE THREAD

**Issue by Toylerrr** [Phalcode/gamevault-backend#284]
**Describe the bug**
Games The Jackbox Party Pack have 1-10 instead of 1,2,3,4... it sorts 1,10,2,3. Sorting by the next character in line.

![image](https://github.com/Phalcode/gamevault-backend/assets/4400902/29179525-115a-4083-96fa-233c9fd65a68)

**Comment by Alfagun74** [comment]
Good ol' lexicographic sorting problem. I will see what i can do about it. 😆

**Comment by Alfagun74** [comment]
the cleanest solution would be if we got the results sorted correctly from the DB already so i forwarded this issue to our pagination library https://github.com/ppetzold/nestjs-paginate/issues/907

**Comment by Alfagun74** [comment]
More info:
- https://en.wikipedia.org/wiki/Natural_sort_order
- https://stackoverflow.com/a/16520873

**Comment by Alfagun74** [comment]
Well...
https://github.com/ppetzold/nestjs-paginate/issues/907

Fuck this, I guess. 🫠 

Too complex for such a nickpicky issue. If I sort the data after pulling it from my DB or in the client it would break with my pagination, so it seems like you'll have to live with it, im sorry.



![Image](https://github.com/Phalcode/gamevault-backend/assets/22225051/9a64952a-13c9-4f69-bb46-4973fd9d853c)
