### ISSUE TITLE
Add encryption support for PostgreSQL Client

### ISSUE THREAD

**Issue by hostmatic** [Phalcode/gamevault-backend#285]
**Is your feature request related to a problem? Please describe.**
When deploying Gamevault's PostgreSQL to another server (example Azure PostgreSQL) encryption demands for TLS does so the Gamevault Backend cannot connect to the database since login request aren't encrypted.
See: https://learn.microsoft.com/en-us/azure/postgresql/single-server/how-to-tls-configurations

**Describe the solution you'd like**
Add option to connect to an PostgreSQL database with encryption.

**Describe alternatives you've considered**
None in this scenario

**Comment by Alfagun74** [comment]
Thanks for the feature request, i will see what i can do about this.

**Comment by Alfagun74** [comment]
Will be implemented in the upcoming update. Thank you so much!

**Comment by hostmatic** [comment]
Hello, thanks for following up! One quick question, is the Postgresql server certificate required in the container for establishing a connection? And if so how one would pass it to the container?

**Comment by Alfagun74** [comment]
hi @hostmatic you will need one, depending on your provider and you will be able to mount them as files in the respective mount-points. [Docs are already live](https://gamevau.lt/docs/server-docs/configuration#games:~:text=DB_TLS_CERTIFICATE_PATH). (Update coming soon)
