### ISSUE TITLE
No "Installed Games" & "Server Games" after host + application reboot

### ISSUE THREAD

**Issue by casudo** [Phalcode/gamevault-backend#290]
**Describe the bug**
Yet another issue (?) I've encountered today. I've restarted my Proxmox host, in which my Ubuntu VM is running GameVault Server as Docker container. 

When I opened GameVault on my Windows 10 machine, it showed 0 installed games (despite having one game installed via GameVault) and 0 server games (I have 15 server games which I verified are also mounted inside the Docker container at /files). Also, the download tab is empty.

**/files inside the GameVault Server:**
![image](https://github.com/Phalcode/gamevault-app/assets/55252063/2a0ad73e-d304-4da1-bae9-bcb0c55ab590)

**GameVault Server log lines as soon as I start GameVault on my desktop:**
![image](https://github.com/Phalcode/gamevault-app/assets/55252063/2e34c281-b9a0-428b-80dc-cfa36fa5de83)

As you can see, it also found those 15 games, but won't display them in the GUI.
![image](https://github.com/Phalcode/gamevault-app/assets/55252063/9fcc3c47-5230-4d63-a0c8-4106f03b9772)

I did not tinker with any file or folder permissions. I've just restarted my host system.

**To Reproduce**
1. Restart the whole Docker host

**Expected behavior**
The installed and server games should be shown correctly in the GUI.

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - Windows 10

**Comment by Alfagun74** [comment]
Hi @casudo, im sorry but i cannot reproduce the issue.

I tried creating 2 archives via sevenzip, one password protected, and both populated fine.

Can you provide me a small encrypted file that produces this error?

**Comment by Alfagun74** [comment]
Moved into #297
