### ISSUE TITLE
Cloudflare Proxy Content-Length Header Issue GameVault

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-backend#294]
**Description**:
When proxying a subdomain through Cloudflare, I get a content length error with the TrueCharts GameVault application on TrueNAS Scale. This issue occurs because Cloudflare strips away the Content-Length header, which is needed by GameVault for download progress.

**Details**:
- **Problem**: Content-Length header stripped by Cloudflare causes errors in GameVault.
- **Proposed Solution**:
  - Implement a fallback Content-Length header that Cloudflare does not strip.

TODO:
- [x] Implement header "X-Download-Size" in Download responses.
- [ ] Client using "X-Download-Size" if "Content-Length" is not given.

**Comment by SkyLostTR** [comment]
Waiting on this myself as well.

**Comment by Alfagun74** [comment]
implemented on serverside.

**Comment by Yelo420** [comment]
implemented on clientside
