### ISSUE TITLE
New additions to GameVault not being indexed properly if they are different versions of a title that already exists.

### ISSUE THREAD

**Issue by Kudjo-Grand** [Phalcode/gamevault-backend#303]
Currently, how does Gamevault handle different versions of the same game? I thought it handled it as a totally seperate title.

I just added a different version of the same game (the fourth discrete version) and not only did it NOT show up, but the other two entries don't show up in the client search anymore.

Example:
game v1.01 - added, showed up as expected in client
game v1.06 - added, showed up as expected in client
game v1.13 - added, didn't show up in client searches
game v1.27 - added, didn't show up in client searches, and also lost access to all previous entries except v1.01

I've tried moving the "game (v1.27) (W_P) (2024).zip" file out of gamevault directories and then putting it back in. Didn't help. I've tried restarting the server. Didn't help.

I'm not sure what else to test. 

Any ideas of something to try?

**Comment by Alfagun74** [comment]
​https://gamevau.lt/docs/server-docs/adding-games#adding-the-same-game-multiple-times

**Comment by Kudjo-Grand** [comment]
In other words: RTFM. 

So, sorry. I really thought that I'd done it with just the version being different in the past, but I noticed that those other files had other slight differences, that made them unique entires to GV.

Thank you.
