### ISSUE TITLE
Parental Control

### ISSUE THREAD

**Issue by UnholyVision** [Phalcode/gamevault-backend#304]
**Describe the solution you'd like**
I would like to see ratings for games from ESRB & PEGI implemented in when valid. If say you look at Steam and the game BattleBlock Theater as an example. It list "T" on the game and the reasons for it. Then if a game can't find one, an admin can add a custom rating. These ratings can then be applied to permissions per user account to what they can access. 

**Describe alternatives you've considered**
If ESRB & PEGI are not possible, then a tagging system would be nice. Perhaps in the games folder one could make a "metadata.txt" file or something. The scan would pick that up and assign a tag which you could then apply to each users access level.

**Additional context**
This would be great for being an active parent in my game collection, where the old children couldn't just play games I didn't want them to.

**Comment by Alfagun74** [comment]
Implemented in v13

**Comment by Alfagun74** [comment]
Needs the birth date form in client (Registration & User Edit)

**Comment by Alfagun74** [comment]
Requires a final test

**Comment by Alfagun74** [comment]
Only needs "translation" of igdb age ratings, then its complete.

**Comment by UnholyVision** [comment]
> Hey @UnholyVision,
> 
> It's been a while! RAWG is no more and im rewriting half of the backend anyway so i started implementing this for the major v13. I wanted to give you an update on the current progress. Here’s what the new features will look like:
> 
> * [x]  Administrators can set an Age of Majority for the server (default is 18) and require a birthdate for registration.
> * [x]  Users can change their birthday, provided they are over the Age of Majority. If they are underage, an admin must change it.
> * [x]  Metadata providers and Administrators can set minimum age requirements for games using a simple integer. For the built-in providers, i will map various rating systems, such as PEGI and ESRB, to their respective ages (e.g., PEGI 16 -> 16).
> * [x]  Games and Progresses for Games that require an age older than the user's age will be hidden from the user.
> 
> Really hope you're still interested in this feature 😅

Sorry for the very late reply. Though, yes I am and thank you for this.
