### ISSUE TITLE
add sorting title to metadata table 

### ISSUE THREAD

**Issue by sentrywasbored** [Phalcode/gamevault-backend#310]
**Is your feature request related to a problem? Please describe.**
With many game series' in gamevault and other game organizers, games are sorted out of order due to not being explicitly labeled with their numbered entry. One example of which is the LEGO Batman trilogy where due to the game's title, it gets sorted as LEGO Batman T... instead of LEGO Batman 1... putting it at the far end of the series on the organizational chart. This is especially prevalent on game series without numbered entries yet are very much set in order like the Harry Potter games (which in the current situation, sort out to a comically disordered 2,7,8,4,6,5,3,1).

**Describe the solution you'd like**
an optional addition to the sqlite/postgresdb database in the form of a sorting title would allow a server administrator to manually correct such errors and effectively organize such game series to their rightful order.

**Additional context**
I have already completed the client-side work for this feature and have completed ~50% of the work needed server-side as well. All that is required as of now is to add sort_title to the database schema and modify the title-based sorter to use sort_title for data with title as a fallback if sort_title returns "" or null.

**Comment by Alfagun74** [comment]
i even went a bit further and built a default algorithm for this. It converts the title to lowercase, removes leading articles (like "the", "a", "an"), strips special characters (except alphanumeric and spaces), collapses multiple spaces into one, and trims any extra spaces.
