### ISSUE TITLE
Document GameType Linux

### ISSUE THREAD

**Issue by alexfornuto** [Phalcode/gamevault-backend#323]
I was halfway through writing this issue to request a Linux game type, when I noticed that I could filter on it in the client. I didn't know it existed because it's not in the docs. Please update the documentation to let us know what the naming convention is.

**Comment by alexfornuto** [comment]
@Alfagun74 Mind telling me the convention here while we wait for the docs update?

**Comment by Alfagun74** [comment]
Currently the only way to detect a game as Linux Portable is by having .sh files inside an archive or as a single file executable.

**Comment by Alfagun74** [comment]
thanks for reporting the missing docs!

**Comment by alexfornuto** [comment]
> Currently the only way to detect a game as Linux Portable is by having .sh files inside an archive or as a single file executable.

But... the docs update you just made says:

> Determined by the type tag override...

Does the override not work?

**Comment by Alfagun74** [comment]
override always works. just put (L_P) into the game title.
